
services:
  bot:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "glitch-bot"

    volumes:
      - ../app/:/app/
      - ../.env:/app/.env

    ports:
      - "5690:5691"

    command: "debugpy --listen 0.0.0.0:5691 main.py"
