
services:
  bot_consumer:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: "bot-faststream"

    environment:
      KAFKA_URL: ${KAFKA_URL:?}

    volumes:
      - ../app/:/app/
      - ../.env:/app/.env

    ports:
      - "5679:5680"

    command: "debugpy --listen 0.0.0.0:5680 -m faststream run --factory consumers.main:get_app --reload"
